apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-${{values.entity_name | lower | replace(' ','-')}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
    - host: ${{ values.domain }}
      http:
        paths:
          - path: ${{ values.path }}
            pathType: Prefix
            backend:
              service:
                name: ${{values.entity_name | lower | replace(' ','-')}}
                port:
                  number: 80
  tls:
    - hosts:
        - ${{ values.domain }}
      secretName: ${{values.entity_name | lower | replace(' ','-')}}-secret
