apiVersion: v1
kind: Service
metadata:
  name: ${{ values.entity_name | lower | replace(' ','-')  }}
  labels:
    backstage.io/kubernetes-id: ${{ values.entity_name | lower | replace(' ','-')  }}
    app: ${{ values.entity_name | lower | replace(' ','-')  }}
spec:
  type: ClusterIP
  selector:
    app: ${{ values.entity_name | lower | replace(' ','-')  }}
  ports:
    - name: default
      port: 80
      protocol: TCP
      targetPort: 3000
